artifact_uri: /Users/rishavgupta/Desktop/mlops/mlops_assignment/experiment_tracking/242041841724677674/75cbdc4a5d44468fb17fb0761e4edc0e/artifacts
end_time: 1778408770084
entry_point_name: ''
experiment_id: '242041841724677674'
lifecycle_stage: active
run_id: 75cbdc4a5d44468fb17fb0761e4edc0e
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1778408765810
status: 3
tags: []
user_id: rishavgupta
