artifact_uri: /Users/rishavgupta/Desktop/mlops/mlops_assignment/experiment_tracking/242041841724677674/94234b1cad9b498594f5c23b94dd4fa0/artifacts
end_time: 1777881947777
entry_point_name: ''
experiment_id: '242041841724677674'
lifecycle_stage: active
run_id: 94234b1cad9b498594f5c23b94dd4fa0
run_name: LogisticRegression
source_name: ''
source_type: 4
source_version: ''
start_time: 1777881942785
status: 3
tags: []
user_id: rishavgupta
