artifact_uri: /Users/rishavgupta/Desktop/mlops/mlops_assignment/experiment_tracking/242041841724677674/887f1578daa54241b92b6b9196c0deaa/artifacts
end_time: 1778408775627
entry_point_name: ''
experiment_id: '242041841724677674'
lifecycle_stage: active
run_id: 887f1578daa54241b92b6b9196c0deaa
run_name: GradientBoosting
source_name: ''
source_type: 4
source_version: ''
start_time: 1778408772928
status: 3
tags: []
user_id: rishavgupta
