artifact_uri: /Users/rishavgupta/Desktop/mlops/mlops_assignment/experiment_tracking/242041841724677674/fb6c1f68a96e44409c08cfb570fa0249/artifacts
end_time: 1778409979109
entry_point_name: ''
experiment_id: '242041841724677674'
lifecycle_stage: active
run_id: fb6c1f68a96e44409c08cfb570fa0249
run_name: RandomForest
source_name: ''
source_type: 4
source_version: ''
start_time: 1778409976443
status: 3
tags: []
user_id: rishavgupta
